id: AB993211B
title: CXII_4. Deep marks, and how they are fastened
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.018558
  last_modified_at: 2022-03-01 21:15:21.018561
