id: AB993211B
title: CXXIII_2. Rewards of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.071428
  last_modified_at: 2022-03-01 21:15:21.071430
