id: AB993211B
title: CIII_4. Perfect wisdom, and the other perfections
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.924376
  last_modified_at: 2022-03-01 21:15:20.924381
