id: AB993211B
title: CXXVIII_5. Extinction, non-extinction and perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.101344
  last_modified_at: 2022-03-01 21:15:21.101346
