id: AB993211B
title: CXXX_2. Sadaprarudita’s self sacrifice
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.127464
  last_modified_at: 2022-03-01 21:15:21.127467
