id: AB993211B
title: CXIX_5. Prediction of the goddess of the Ganges
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.031671
  last_modified_at: 2022-03-01 21:15:21.031674
