id: AB993211B
title: CXII_3. How the Tathagata knows the thoughts of beings*
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.016314
  last_modified_at: 2022-03-01 21:15:21.016318
