id: AB993211B
title: CXVI_1. Tathagata-suchness
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.057576
  last_modified_at: 2022-03-01 21:15:21.057580
