id: AB993211B
title: CXXVI_1. Sakra praises the bodhisattvas
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.111382
  last_modified_at: 2022-03-01 21:15:21.111385
