id: AB993211B
title: CVII_5. Causes of belief in the perfection of wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.985677
  last_modified_at: 2022-03-01 21:15:20.985680
