id: AB993211B
title: CXXVIII_2. Praise of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.097647
  last_modified_at: 2022-03-01 21:15:21.097650
