id: AB993211B
title: CX_5. right attitude to perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.145238
  last_modified_at: 2022-03-01 21:15:21.145240
