id: AB993211B
title: CXXII_2. Emptiness, defilements and purification
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.074285
  last_modified_at: 2022-03-01 21:15:21.074288
