id: AB993211B
title: CXV_1. The beginner’s task
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.065134
  last_modified_at: 2022-03-01 21:15:21.065136
