id: AB993211B
title: CXVII_3. More tokens of irreversibility
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.055907
  last_modified_at: 2022-03-01 21:15:21.055910
