id: AB993211B
title: CXXVII_5. Emptiness and dwelling in perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.110098
  last_modified_at: 2022-03-01 21:15:21.110100
