id: AB993211B
title: CXIV_2. Past deeds of a bodhisattva who fails in perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.022807
  last_modified_at: 2022-03-01 21:15:21.022810
