id: AB993211B
title: CXXIV_2. The bodhisattva’s rigth attitude to other bodhisattvas
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.081108
  last_modified_at: 2022-03-01 21:15:21.081111
