id: AB993211B
title: CXI_6. More discord between teacher and pupil
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.039816
  last_modified_at: 2022-03-01 21:15:21.039819
