id: AB993211B
title: CXI_4. Sources of discord between teacher and pupil
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.036662
  last_modified_at: 2022-03-01 21:15:21.036665
