id: AB993211B
title: CXXI_2. Pride in connection with the annunciation of the name
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.093485
  last_modified_at: 2022-03-01 21:15:21.093488
