id: AB993211B
title: CII_6. The infinitude of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.940757
  last_modified_at: 2022-03-01 21:15:20.940760
