id: AB993211B
title: CIV_1. Relative value of tathagata-relics and of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.945840
  last_modified_at: 2022-03-01 21:15:20.945845
