id: AB993211B
title: CVII_1. Hymm to the perfection of wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.979666
  last_modified_at: 2022-03-01 21:15:20.979669
