id: AB993211B
title: CXVIII_5. No growth or diminution
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.050098
  last_modified_at: 2022-03-01 21:15:21.050100
