id: AB993211B
title: CVII_2. Predominance of perfect wisdom over the other perfections
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.980951
  last_modified_at: 2022-03-01 21:15:20.980967
