id: AB993211B
title: CXXX_3. Dharma_udgata’s demonstration of dharma
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.129296
  last_modified_at: 2022-03-01 21:15:21.129299
