id: AB993211B
title: CV_1. The perfection of wisdom a source of great merit
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.997678
  last_modified_at: 2022-03-01 21:15:20.997681
