id: AB993211B
title: CXII_2. How the Tathagata knows the world
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.011414
  last_modified_at: 2022-03-01 21:15:21.011417
