id: AB993211B
title: CXXIV_1. Conditions which open a bodhisattva to Mara’s influence
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.079566
  last_modified_at: 2022-03-01 21:15:21.079569
