id: AB993211B
title: CXVI_5. Requisites of going forth to enlightenment
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.064006
  last_modified_at: 2022-03-01 21:15:21.064009
