id: AB993211B
title: CII_7. Confirmation
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.943411
  last_modified_at: 2022-03-01 21:15:20.943419
