id: AB993211B
title: CX_1. Past deeds, and the present attitude to perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.139854
  last_modified_at: 2022-03-01 21:15:21.139857
