id: AB993211B
title: CXV_2. How a bodhisattva helps beings
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.066199
  last_modified_at: 2022-03-01 21:15:21.066201
