id: AB993211B
title: CXX_5. Dream experiences and the mark of irreversibility
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.136839
  last_modified_at: 2022-03-01 21:15:21.136842
