id: AB993211B
title: CX_2. Qualifications of a bodhisattva who obtains perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.141338
  last_modified_at: 2022-03-01 21:15:21.141341
