id: AB993211B
title: CXXII_3. Attentions to perfect wisdom, and the pearl of great price
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.075827
  last_modified_at: 2022-03-01 21:15:21.075830
