id: AB993211B
title: CXVII_1. Various tokens of irreversibility
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.052029
  last_modified_at: 2022-03-01 21:15:21.052032
