id: AB993211B
title: CXIV_3. Four similes
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.024133
  last_modified_at: 2022-03-01 21:15:21.024136
