id: AB993211B
title: CIII_2. The cult of perfect wisdom compared with the cult of the buddhas
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.918152
  last_modified_at: 2022-03-01 21:15:20.918158
