id: AB993211B
title: CVII_4. Why the perfection of wisdom is great
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.984196
  last_modified_at: 2022-03-01 21:15:20.984199
