id: AB993211B
title: CXVI_4. Enlightenment and emptiness
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.062567
  last_modified_at: 2022-03-01 21:15:21.062569
