id: AB993211B
title: CVIII_1. Depth and purity of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.971432
  last_modified_at: 2022-03-01 21:15:20.971434
