id: AB993211B
title: CXX_6. Irreversibility and the magical power of veracity
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.138313
  last_modified_at: 2022-03-01 21:15:21.138315
