id: AB993211B
title: CVI_1. Supreme merit of dedication and jubilation
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.988981
  last_modified_at: 2022-03-01 21:15:20.988984
