id: AB993211B
title: CXXV_3. The perfection of wisdom comprehends all perfections
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.118360
  last_modified_at: 2022-03-01 21:15:21.118363
