id: AB993211B
title: CXVI_3. Perfect wisdom and skill in means
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.060792
  last_modified_at: 2022-03-01 21:15:21.060795
