id: AB993211B
title: CV_3. The perfection of wisdom greater than any other spiritual gift
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.003051
  last_modified_at: 2022-03-01 21:15:21.003057
