id: AB993211B
title: CXX_4. Irreversibility
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.134561
  last_modified_at: 2022-03-01 21:15:21.134564
