id: AB993211B
title: CXXV_5. Bodhisattvas and disciples
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.120938
  last_modified_at: 2022-03-01 21:15:21.120941
