id: AB993211B
title: CXV_3. Description of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.068463
  last_modified_at: 2022-03-01 21:15:21.068466
