id: AB993211B
title: CI_3. The meaning of ’Bodhisattva’
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.963571
  last_modified_at: 2022-03-01 21:15:20.963574
