id: AB993211B
title: CVI_4. How perverted views can be avoided
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.993570
  last_modified_at: 2022-03-01 21:15:20.993573
