id: AB993211B
title: CX_8. Prediction about spread of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.149031
  last_modified_at: 2022-03-01 21:15:21.149034
