id: AB993211B
title: CXXII_1. The good friends
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.073014
  last_modified_at: 2022-03-01 21:15:21.073018
