id: AB993211B
title: CIII_1. Worldly advantages of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.914758
  last_modified_at: 2022-03-01 21:15:20.914769
