id: AB993211B
title: CXI_8. Antagonism between Mara and Buddha
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.041638
  last_modified_at: 2022-03-01 21:15:21.041641
