id: AB993211B
title: CXXV_1. How a bodhisattva is trained in all-knowledge
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.115548
  last_modified_at: 2022-03-01 21:15:21.115551
