id: AB993211B
title: CIII_3. Perfect wisdom, a great spell
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.922264
  last_modified_at: 2022-03-01 21:15:20.922269
