id: AB993211B
title: CXIII_1. Five attributes of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.004747
  last_modified_at: 2022-03-01 21:15:21.004751
