id: AB993211B
title: CI_4. The meaning of ’great being’
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.965669
  last_modified_at: 2022-03-01 21:15:20.965672
