id: AB993211B
title: CXXVII_1. The bodhisattva’s courage in difficulties
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.104767
  last_modified_at: 2022-03-01 21:15:21.104770
