id: AB993211B
title: CIX_2. Effects of perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.952298
  last_modified_at: 2022-03-01 21:15:20.952301
