id: AB993211B
title: CVII_3. Nothing procured by perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.982903
  last_modified_at: 2022-03-01 21:15:20.982906
