id: AB993211B
title: CXXXI_2. The perfection of wisdom entrusted to Ananda
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.123684
  last_modified_at: 2022-03-01 21:15:21.123687
