id: AB993211B
title: CII_3. The saints and their goal are illusions
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.934632
  last_modified_at: 2022-03-01 21:15:20.934637
