id: AB993211B
title: CXIII_3. Nothing to take hold of
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.007497
  last_modified_at: 2022-03-01 21:15:21.007501
