id: AB993211B
title: CXII_5. The world shown as empty
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.020212
  last_modified_at: 2022-03-01 21:15:21.020215
