id: AB993211B
title: CXXVI_3. The nature of illusion
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.114311
  last_modified_at: 2022-03-01 21:15:21.114314
