id: AB993211B
title: CXXIX_2. Description of Gandhavati, and of Dharma_udgata’s life
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.083967
  last_modified_at: 2022-03-01 21:15:21.083970
