id: AB993211B
title: CXVIII_2. How to attend to perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.044456
  last_modified_at: 2022-03-01 21:15:21.044459
