id: AB993211B
title: CXXVIII_4. Akshobhya’s buddha-field
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.099967
  last_modified_at: 2022-03-01 21:15:21.099970
