id: AB993211B
title: CXXVIII_6. Advantages derived from perfect wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.103128
  last_modified_at: 2022-03-01 21:15:21.103131
