id: AB993211B
title: CX_3. Five similes to illustrate nearness to full enlightenment
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.142679
  last_modified_at: 2022-03-01 21:15:21.142682
