id: AB993211B
title: CIV_3. Supreme value of the perfection of wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.949099
  last_modified_at: 2022-03-01 21:15:20.949102
