id: AB993211B
title: CXXX_1. The coming and going of the tathagatas
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.125013
  last_modified_at: 2022-03-01 21:15:21.125016
