id: AB993211B
title: CXI_2. The perfection of wisdom and the sutras of the disciples
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.033985
  last_modified_at: 2022-03-01 21:15:21.033988
