id: AB993211B
title: CII_2. How to stand in emptiness, or the perfection of wisdom
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.932237
  last_modified_at: 2022-03-01 21:15:20.932241
