id: AB993211B
title: CXXVII_2. The bodhisattva protected by the gods and against Mara
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.105925
  last_modified_at: 2022-03-01 21:15:21.105928
