id: AB993211B
title: CXXVII_4. Enlightenment and suchness
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.108540
  last_modified_at: 2022-03-01 21:15:21.108543
