id: AB993211B
title: 29. Parivarta
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:20.907689
  last_modified_at: 2022-03-01 21:15:20.907707
