id: AB993211B
title: CXVIII_3. Merit
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.046262
  last_modified_at: 2022-03-01 21:15:21.046265
