id: AB993211B
title: CXXI_3. Faults in connection with detachment
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.095024
  last_modified_at: 2022-03-01 21:15:21.095027
