id: AB993211B
title: CXIII_2. Spiritual rebirth resulting from this knowledge
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.006093
  last_modified_at: 2022-03-01 21:15:21.006096
