id: AB993211B
title: CXXVII_3. The buddhas praise the bodhisattva
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:15:21.107265
  last_modified_at: 2022-03-01 21:15:21.107268
